# Generated by Django 4.2.6 on 2023-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('depaartment', models.CharField(max_length=200)),
                ('salary', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
